config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :snap_event_lists
  resources :game_configs
  resources :snapshots
  resources :game_statuses
  resources :games
  resources :player_statuses
  resources :subscriptions

end

app/models/snap_event_list.rb
class SnapEventList < ActiveRecord::Base
end

app/controllers/snap_event_lists_controller.rb
class SnapEventListsController < ApplicationController
  before_action :set_snap_event_list, only: [:show, :edit, :update, :destroy]

  # GET /snap_event_lists
  # GET /snap_event_lists.json
  def index
    @snap_event_lists = SnapEventList.all
  end

  # GET /snap_event_lists/1
  # GET /snap_event_lists/1.json
  def show
  end

  # GET /snap_event_lists/new
  def new
    @snap_event_list = SnapEventList.new
  end

  # GET /snap_event_lists/1/edit
  def edit
  end

  # POST /snap_event_lists
  # POST /snap_event_lists.json
  def create
    @snap_event_list = SnapEventList.new(snap_event_list_params)

    respond_to do |format|
      if @snap_event_list.save
        format.html { redirect_to @snap_event_list, notice: 'Snap event list was successfully created.' }
        format.json { render :show, status: :created, location: @snap_event_list }
      else
        format.html { render :new }
        format.json { render json: @snap_event_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /snap_event_lists/1
  # PATCH/PUT /snap_event_lists/1.json
  def update
    respond_to do |format|
      if @snap_event_list.update(snap_event_list_params)
        format.html { redirect_to @snap_event_list, notice: 'Snap event list was successfully updated.' }
        format.json { render :show, status: :ok, location: @snap_event_list }
      else
        format.html { render :edit }
        format.json { render json: @snap_event_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /snap_event_lists/1
  # DELETE /snap_event_lists/1.json
  def destroy
    @snap_event_list.destroy
    respond_to do |format|
      format.html { redirect_to snap_event_lists_url, notice: 'Snap event list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_snap_event_list
      @snap_event_list = SnapEventList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def snap_event_list_params
      params.require(:snap_event_list).permit(:snapEventListID, :snapEventType, :eventListTimeStamp, :snapEvent1, :snapEvent2, :snapEvent3, :snapEvent4, :snapEvent5, :snapEvent6, :snapEvent7, :snapEvent8, :snapEvent9, :snapEvent10)
    end
end

app/helpers/snap_event_lists_helper.rb
module SnapEventListsHelper
end

app/views/snap_event_lists/_form.html.erb
<%= form_for(@snap_event_list) do |f| %>
  <% if @snap_event_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@snap_event_list.errors.count, "error") %> prohibited this snap_event_list from being saved:</h2>

      <ul>
      <% @snap_event_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :snapEventListID %><br>
    <%= f.number_field :snapEventListID %>
  </div>
  <div class="field">
    <%= f.label :snapEventType %><br>
    <%= f.text_field :snapEventType %>
  </div>
  <div class="field">
    <%= f.label :eventListTimeStamp %><br>
    <%= f.text_field :eventListTimeStamp %>
  </div>
  <div class="field">
    <%= f.label :snapEvent1 %><br>
    <%= f.number_field :snapEvent1 %>
  </div>
  <div class="field">
    <%= f.label :snapEvent2 %><br>
    <%= f.number_field :snapEvent2 %>
  </div>
  <div class="field">
    <%= f.label :snapEvent3 %><br>
    <%= f.number_field :snapEvent3 %>
  </div>
  <div class="field">
    <%= f.label :snapEvent4 %><br>
    <%= f.number_field :snapEvent4 %>
  </div>
  <div class="field">
    <%= f.label :snapEvent5 %><br>
    <%= f.number_field :snapEvent5 %>
  </div>
  <div class="field">
    <%= f.label :snapEvent6 %><br>
    <%= f.number_field :snapEvent6 %>
  </div>
  <div class="field">
    <%= f.label :snapEvent7 %><br>
    <%= f.number_field :snapEvent7 %>
  </div>
  <div class="field">
    <%= f.label :snapEvent8 %><br>
    <%= f.number_field :snapEvent8 %>
  </div>
  <div class="field">
    <%= f.label :snapEvent9 %><br>
    <%= f.text_field :snapEvent9 %>
  </div>
  <div class="field">
    <%= f.label :snapEvent10 %><br>
    <%= f.text_field :snapEvent10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/snap_event_lists/edit.html.erb
<h1>Editing Snap Event List</h1>

<%= render 'form' %>

<%= link_to 'Show', @snap_event_list %> |
<%= link_to 'Back', snap_event_lists_path %>

app/views/snap_event_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Snap Event Lists</h1>

<table>
  <thead>
    <tr>
      <th>Snapeventlistid</th>
      <th>Snapeventtype</th>
      <th>Eventlisttimestamp</th>
      <th>Snapevent1</th>
      <th>Snapevent2</th>
      <th>Snapevent3</th>
      <th>Snapevent4</th>
      <th>Snapevent5</th>
      <th>Snapevent6</th>
      <th>Snapevent7</th>
      <th>Snapevent8</th>
      <th>Snapevent9</th>
      <th>Snapevent10</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @snap_event_lists.each do |snap_event_list| %>
      <tr>
        <td><%= snap_event_list.snapEventListID %></td>
        <td><%= snap_event_list.snapEventType %></td>
        <td><%= snap_event_list.eventListTimeStamp %></td>
        <td><%= snap_event_list.snapEvent1 %></td>
        <td><%= snap_event_list.snapEvent2 %></td>
        <td><%= snap_event_list.snapEvent3 %></td>
        <td><%= snap_event_list.snapEvent4 %></td>
        <td><%= snap_event_list.snapEvent5 %></td>
        <td><%= snap_event_list.snapEvent6 %></td>
        <td><%= snap_event_list.snapEvent7 %></td>
        <td><%= snap_event_list.snapEvent8 %></td>
        <td><%= snap_event_list.snapEvent9 %></td>
        <td><%= snap_event_list.snapEvent10 %></td>
        <td><%= link_to 'Show', snap_event_list %></td>
        <td><%= link_to 'Edit', edit_snap_event_list_path(snap_event_list) %></td>
        <td><%= link_to 'Destroy', snap_event_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Snap event list', new_snap_event_list_path %>

app/views/snap_event_lists/new.html.erb
<h1>New Snap Event List</h1>

<%= render 'form' %>

<%= link_to 'Back', snap_event_lists_path %>

app/views/snap_event_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Snapeventlistid:</strong>
  <%= @snap_event_list.snapEventListID %>
</p>

<p>
  <strong>Snapeventtype:</strong>
  <%= @snap_event_list.snapEventType %>
</p>

<p>
  <strong>Eventlisttimestamp:</strong>
  <%= @snap_event_list.eventListTimeStamp %>
</p>

<p>
  <strong>Snapevent1:</strong>
  <%= @snap_event_list.snapEvent1 %>
</p>

<p>
  <strong>Snapevent2:</strong>
  <%= @snap_event_list.snapEvent2 %>
</p>

<p>
  <strong>Snapevent3:</strong>
  <%= @snap_event_list.snapEvent3 %>
</p>

<p>
  <strong>Snapevent4:</strong>
  <%= @snap_event_list.snapEvent4 %>
</p>

<p>
  <strong>Snapevent5:</strong>
  <%= @snap_event_list.snapEvent5 %>
</p>

<p>
  <strong>Snapevent6:</strong>
  <%= @snap_event_list.snapEvent6 %>
</p>

<p>
  <strong>Snapevent7:</strong>
  <%= @snap_event_list.snapEvent7 %>
</p>

<p>
  <strong>Snapevent8:</strong>
  <%= @snap_event_list.snapEvent8 %>
</p>

<p>
  <strong>Snapevent9:</strong>
  <%= @snap_event_list.snapEvent9 %>
</p>

<p>
  <strong>Snapevent10:</strong>
  <%= @snap_event_list.snapEvent10 %>
</p>

<%= link_to 'Edit', edit_snap_event_list_path(@snap_event_list) %> |
<%= link_to 'Back', snap_event_lists_path %>