config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :snap_event_lists
  resources :game_configs
  resources :snapshots
  resources :game_statuses
  resources :games
  resources :player_statuses
  resources :subscriptions

end

app/models/game_config.rb
class GameConfig < ActiveRecord::Base
end

app/controllers/game_configs_controller.rb
class GameConfigsController < ApplicationController
  before_action :set_game_config, only: [:show, :edit, :update, :destroy]

  # GET /game_configs
  # GET /game_configs.json
  def index
    @game_configs = GameConfig.all
  end

  # GET /game_configs/1
  # GET /game_configs/1.json
  def show
  end

  # GET /game_configs/new
  def new
    @game_config = GameConfig.new
  end

  # GET /game_configs/1/edit
  def edit
  end

  # POST /game_configs
  # POST /game_configs.json
  def create
    @game_config = GameConfig.new(game_config_params)

    respond_to do |format|
      if @game_config.save
        format.html { redirect_to @game_config, notice: 'Game config was successfully created.' }
        format.json { render :show, status: :created, location: @game_config }
      else
        format.html { render :new }
        format.json { render json: @game_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_configs/1
  # PATCH/PUT /game_configs/1.json
  def update
    respond_to do |format|
      if @game_config.update(game_config_params)
        format.html { redirect_to @game_config, notice: 'Game config was successfully updated.' }
        format.json { render :show, status: :ok, location: @game_config }
      else
        format.html { render :edit }
        format.json { render json: @game_config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_configs/1
  # DELETE /game_configs/1.json
  def destroy
    @game_config.destroy
    respond_to do |format|
      format.html { redirect_to game_configs_url, notice: 'Game config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game_config
      @game_config = GameConfig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_config_params
      params.require(:game_config).permit(:gameConfigID, :gameID, :gameConfP1, :gameConfP2, :gameConfP3, :gameConfP4, :gameConfP5, :gameConfP6, :gameConfP7, :gameConfP8, :gameConfP9, :gameConfP10)
    end
end

app/helpers/game_configs_helper.rb
module GameConfigsHelper
end

app/views/game_configs/_form.html.erb
<%= form_for(@game_config) do |f| %>
  <% if @game_config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game_config.errors.count, "error") %> prohibited this game_config from being saved:</h2>

      <ul>
      <% @game_config.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :gameConfigID %><br>
    <%= f.number_field :gameConfigID %>
  </div>
  <div class="field">
    <%= f.label :gameID %><br>
    <%= f.number_field :gameID %>
  </div>
  <div class="field">
    <%= f.label :gameConfP1 %><br>
    <%= f.text_field :gameConfP1 %>
  </div>
  <div class="field">
    <%= f.label :gameConfP2 %><br>
    <%= f.text_field :gameConfP2 %>
  </div>
  <div class="field">
    <%= f.label :gameConfP3 %><br>
    <%= f.text_field :gameConfP3 %>
  </div>
  <div class="field">
    <%= f.label :gameConfP4 %><br>
    <%= f.text_field :gameConfP4 %>
  </div>
  <div class="field">
    <%= f.label :gameConfP5 %><br>
    <%= f.text_field :gameConfP5 %>
  </div>
  <div class="field">
    <%= f.label :gameConfP6 %><br>
    <%= f.text_field :gameConfP6 %>
  </div>
  <div class="field">
    <%= f.label :gameConfP7 %><br>
    <%= f.text_field :gameConfP7 %>
  </div>
  <div class="field">
    <%= f.label :gameConfP8 %><br>
    <%= f.text_field :gameConfP8 %>
  </div>
  <div class="field">
    <%= f.label :gameConfP9 %><br>
    <%= f.text_field :gameConfP9 %>
  </div>
  <div class="field">
    <%= f.label :gameConfP10 %><br>
    <%= f.text_field :gameConfP10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/game_configs/edit.html.erb
<h1>Editing Game Config</h1>

<%= render 'form' %>

<%= link_to 'Show', @game_config %> |
<%= link_to 'Back', game_configs_path %>

app/views/game_configs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Game Configs</h1>

<table>
  <thead>
    <tr>
      <th>Gameconfigid</th>
      <th>Gameid</th>
      <th>Gameconfp1</th>
      <th>Gameconfp2</th>
      <th>Gameconfp3</th>
      <th>Gameconfp4</th>
      <th>Gameconfp5</th>
      <th>Gameconfp6</th>
      <th>Gameconfp7</th>
      <th>Gameconfp8</th>
      <th>Gameconfp9</th>
      <th>Gameconfp10</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @game_configs.each do |game_config| %>
      <tr>
        <td><%= game_config.gameConfigID %></td>
        <td><%= game_config.gameID %></td>
        <td><%= game_config.gameConfP1 %></td>
        <td><%= game_config.gameConfP2 %></td>
        <td><%= game_config.gameConfP3 %></td>
        <td><%= game_config.gameConfP4 %></td>
        <td><%= game_config.gameConfP5 %></td>
        <td><%= game_config.gameConfP6 %></td>
        <td><%= game_config.gameConfP7 %></td>
        <td><%= game_config.gameConfP8 %></td>
        <td><%= game_config.gameConfP9 %></td>
        <td><%= game_config.gameConfP10 %></td>
        <td><%= link_to 'Show', game_config %></td>
        <td><%= link_to 'Edit', edit_game_config_path(game_config) %></td>
        <td><%= link_to 'Destroy', game_config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game config', new_game_config_path %>

app/views/game_configs/new.html.erb
<h1>New Game Config</h1>

<%= render 'form' %>

<%= link_to 'Back', game_configs_path %>

app/views/game_configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gameconfigid:</strong>
  <%= @game_config.gameConfigID %>
</p>

<p>
  <strong>Gameid:</strong>
  <%= @game_config.gameID %>
</p>

<p>
  <strong>Gameconfp1:</strong>
  <%= @game_config.gameConfP1 %>
</p>

<p>
  <strong>Gameconfp2:</strong>
  <%= @game_config.gameConfP2 %>
</p>

<p>
  <strong>Gameconfp3:</strong>
  <%= @game_config.gameConfP3 %>
</p>

<p>
  <strong>Gameconfp4:</strong>
  <%= @game_config.gameConfP4 %>
</p>

<p>
  <strong>Gameconfp5:</strong>
  <%= @game_config.gameConfP5 %>
</p>

<p>
  <strong>Gameconfp6:</strong>
  <%= @game_config.gameConfP6 %>
</p>

<p>
  <strong>Gameconfp7:</strong>
  <%= @game_config.gameConfP7 %>
</p>

<p>
  <strong>Gameconfp8:</strong>
  <%= @game_config.gameConfP8 %>
</p>

<p>
  <strong>Gameconfp9:</strong>
  <%= @game_config.gameConfP9 %>
</p>

<p>
  <strong>Gameconfp10:</strong>
  <%= @game_config.gameConfP10 %>
</p>

<%= link_to 'Edit', edit_game_config_path(@game_config) %> |
<%= link_to 'Back', game_configs_path %>