config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :snap_event_lists
  resources :game_configs
  resources :snapshots
  resources :game_statuses
  resources :games
  resources :player_statuses
  resources :subscriptions

end

app/controllers/player_statuses_controller.rb
class PlayerStatusesController < ApplicationController
  before_action :set_player_status, only: [:show, :edit, :update, :destroy]

  # GET /player_statuses
  # GET /player_statuses.json
  def index
    @player_statuses = PlayerStatus.all
  end

  # GET /player_statuses/1
  # GET /player_statuses/1.json
  def show
  end

  # GET /player_statuses/new
  def new
    @player_status = PlayerStatus.new
  end

  # GET /player_statuses/1/edit
  def edit
  end

  # POST /player_statuses
  # POST /player_statuses.json
  def create
    @player_status = PlayerStatus.new(player_status_params)

    respond_to do |format|
      if @player_status.save
        format.html { redirect_to @player_status, notice: 'Player status was successfully created.' }
        format.json { render :show, status: :created, location: @player_status }
      else
        format.html { render :new }
        format.json { render json: @player_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /player_statuses/1
  # PATCH/PUT /player_statuses/1.json
  def update
    respond_to do |format|
      if @player_status.update(player_status_params)
        format.html { redirect_to @player_status, notice: 'Player status was successfully updated.' }
        format.json { render :show, status: :ok, location: @player_status }
      else
        format.html { render :edit }
        format.json { render json: @player_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /player_statuses/1
  # DELETE /player_statuses/1.json
  def destroy
    @player_status.destroy
    respond_to do |format|
      format.html { redirect_to player_statuses_url, notice: 'Player status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player_status
      @player_status = PlayerStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_status_params
      params.require(:player_status).permit(:playerID, :timeStamp, :gameStatus, :gameConfigID, :gameLevel, :gameScore1, :gameScore2, :gameScore3, :gameScore4, :gameScore5, :gameScore6, :gameScore7, :gameScore8, :gameScore9, :gameScore10)
    end
end

app/helpers/player_statuses_helper.rb
module PlayerStatusesHelper
end

app/views/player_statuses/_form.html.erb
<%= form_for(@player_status) do |f| %>
  <% if @player_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player_status.errors.count, "error") %> prohibited this player_status from being saved:</h2>

      <ul>
      <% @player_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :playerID %><br>
    <%= f.number_field :playerID %>
  </div>
  <div class="field">
    <%= f.label :timeStamp %><br>
    <%= f.text_field :timeStamp %>
  </div>
  <div class="field">
    <%= f.label :gameStatus %><br>
    <%= f.number_field :gameStatus %>
  </div>
  <div class="field">
    <%= f.label :gameConfigID %><br>
    <%= f.text_field :gameConfigID %>
  </div>
  <div class="field">
    <%= f.label :gameLevel %><br>
    <%= f.number_field :gameLevel %>
  </div>
  <div class="field">
    <%= f.label :gameScore1 %><br>
    <%= f.number_field :gameScore1 %>
  </div>
  <div class="field">
    <%= f.label :gameScore2 %><br>
    <%= f.number_field :gameScore2 %>
  </div>
  <div class="field">
    <%= f.label :gameScore3 %><br>
    <%= f.number_field :gameScore3 %>
  </div>
  <div class="field">
    <%= f.label :gameScore4 %><br>
    <%= f.number_field :gameScore4 %>
  </div>
  <div class="field">
    <%= f.label :gameScore5 %><br>
    <%= f.number_field :gameScore5 %>
  </div>
  <div class="field">
    <%= f.label :gameScore6 %><br>
    <%= f.number_field :gameScore6 %>
  </div>
  <div class="field">
    <%= f.label :gameScore7 %><br>
    <%= f.number_field :gameScore7 %>
  </div>
  <div class="field">
    <%= f.label :gameScore8 %><br>
    <%= f.number_field :gameScore8 %>
  </div>
  <div class="field">
    <%= f.label :gameScore9 %><br>
    <%= f.number_field :gameScore9 %>
  </div>
  <div class="field">
    <%= f.label :gameScore10 %><br>
    <%= f.number_field :gameScore10 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/player_statuses/edit.html.erb
<h1>Editing Player Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @player_status %> |
<%= link_to 'Back', player_statuses_path %>

app/views/player_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Player Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Playerid</th>
      <th>Timestamp</th>
      <th>Gamestatus</th>
      <th>Gameconfigid</th>
      <th>Gamelevel</th>
      <th>Gamescore1</th>
      <th>Gamescore2</th>
      <th>Gamescore3</th>
      <th>Gamescore4</th>
      <th>Gamescore5</th>
      <th>Gamescore6</th>
      <th>Gamescore7</th>
      <th>Gamescore8</th>
      <th>Gamescore9</th>
      <th>Gamescore10</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @player_statuses.each do |player_status| %>
      <tr>
        <td><%= player_status.playerID %></td>
        <td><%= player_status.timeStamp %></td>
        <td><%= player_status.gameStatus %></td>
        <td><%= player_status.gameConfigID %></td>
        <td><%= player_status.gameLevel %></td>
        <td><%= player_status.gameScore1 %></td>
        <td><%= player_status.gameScore2 %></td>
        <td><%= player_status.gameScore3 %></td>
        <td><%= player_status.gameScore4 %></td>
        <td><%= player_status.gameScore5 %></td>
        <td><%= player_status.gameScore6 %></td>
        <td><%= player_status.gameScore7 %></td>
        <td><%= player_status.gameScore8 %></td>
        <td><%= player_status.gameScore9 %></td>
        <td><%= player_status.gameScore10 %></td>
        <td><%= link_to 'Show', player_status %></td>
        <td><%= link_to 'Edit', edit_player_status_path(player_status) %></td>
        <td><%= link_to 'Destroy', player_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player status', new_player_status_path %>

app/views/player_statuses/new.html.erb
<h1>New Player Status</h1>

<%= render 'form' %>

<%= link_to 'Back', player_statuses_path %>

app/views/player_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Playerid:</strong>
  <%= @player_status.playerID %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @player_status.timeStamp %>
</p>

<p>
  <strong>Gamestatus:</strong>
  <%= @player_status.gameStatus %>
</p>

<p>
  <strong>Gameconfigid:</strong>
  <%= @player_status.gameConfigID %>
</p>

<p>
  <strong>Gamelevel:</strong>
  <%= @player_status.gameLevel %>
</p>

<p>
  <strong>Gamescore1:</strong>
  <%= @player_status.gameScore1 %>
</p>

<p>
  <strong>Gamescore2:</strong>
  <%= @player_status.gameScore2 %>
</p>

<p>
  <strong>Gamescore3:</strong>
  <%= @player_status.gameScore3 %>
</p>

<p>
  <strong>Gamescore4:</strong>
  <%= @player_status.gameScore4 %>
</p>

<p>
  <strong>Gamescore5:</strong>
  <%= @player_status.gameScore5 %>
</p>

<p>
  <strong>Gamescore6:</strong>
  <%= @player_status.gameScore6 %>
</p>

<p>
  <strong>Gamescore7:</strong>
  <%= @player_status.gameScore7 %>
</p>

<p>
  <strong>Gamescore8:</strong>
  <%= @player_status.gameScore8 %>
</p>

<p>
  <strong>Gamescore9:</strong>
  <%= @player_status.gameScore9 %>
</p>

<p>
  <strong>Gamescore10:</strong>
  <%= @player_status.gameScore10 %>
</p>

<%= link_to 'Edit', edit_player_status_path(@player_status) %> |
<%= link_to 'Back', player_statuses_path %>