config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :snap_event_lists
  resources :game_configs
  resources :snapshots
  resources :game_statuses
  resources :games
  resources :player_statuses
  resources :subscriptions

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: [:show, :edit, :update, :destroy]

  # GET /subscriptions
  # GET /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1
  # GET /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
  end

  # POST /subscriptions
  # POST /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: 'Subscription was successfully created.' }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1
  # PATCH/PUT /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: 'Subscription was successfully updated.' }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1
  # DELETE /subscriptions/1.json
  def destroy
    @subscription.destroy
    respond_to do |format|
      format.html { redirect_to subscriptions_url, notice: 'Subscription was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subscription_params
      params.require(:subscription).permit(:subscriptionID, :gameSubsr1, :subscType, :gameSubsr1, :subscType, :gameSubsr1, :subscType, :gameSubsr1, :subscType, :gameSubsr1, :subscType)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= form_for(@subscription) do |f| %>
  <% if @subscription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>

      <ul>
      <% @subscription.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subscriptionID %><br>
    <%= f.number_field :subscriptionID %>
  </div>
  <div class="field">
    <%= f.label :gameSubsr1 %><br>
    <%= f.number_field :gameSubsr1 %>
  </div>
  <div class="field">
    <%= f.label :subscType %><br>
    <%= f.text_field :subscType %>
  </div>
  <div class="field">
    <%= f.label :gameSubsr1 %><br>
    <%= f.number_field :gameSubsr1 %>
  </div>
  <div class="field">
    <%= f.label :subscType %><br>
    <%= f.text_field :subscType %>
  </div>
  <div class="field">
    <%= f.label :gameSubsr1 %><br>
    <%= f.number_field :gameSubsr1 %>
  </div>
  <div class="field">
    <%= f.label :subscType %><br>
    <%= f.text_field :subscType %>
  </div>
  <div class="field">
    <%= f.label :gameSubsr1 %><br>
    <%= f.number_field :gameSubsr1 %>
  </div>
  <div class="field">
    <%= f.label :subscType %><br>
    <%= f.text_field :subscType %>
  </div>
  <div class="field">
    <%= f.label :gameSubsr1 %><br>
    <%= f.number_field :gameSubsr1 %>
  </div>
  <div class="field">
    <%= f.label :subscType %><br>
    <%= f.text_field :subscType %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Subscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Subscriptionid</th>
      <th>Gamesubsr1</th>
      <th>Subsctype</th>
      <th>Gamesubsr1</th>
      <th>Subsctype</th>
      <th>Gamesubsr1</th>
      <th>Subsctype</th>
      <th>Gamesubsr1</th>
      <th>Subsctype</th>
      <th>Gamesubsr1</th>
      <th>Subsctype</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @subscriptions.each do |subscription| %>
      <tr>
        <td><%= subscription.subscriptionID %></td>
        <td><%= subscription.gameSubsr1 %></td>
        <td><%= subscription.subscType %></td>
        <td><%= subscription.gameSubsr1 %></td>
        <td><%= subscription.subscType %></td>
        <td><%= subscription.gameSubsr1 %></td>
        <td><%= subscription.subscType %></td>
        <td><%= subscription.gameSubsr1 %></td>
        <td><%= subscription.subscType %></td>
        <td><%= subscription.gameSubsr1 %></td>
        <td><%= subscription.subscType %></td>
        <td><%= link_to 'Show', subscription %></td>
        <td><%= link_to 'Edit', edit_subscription_path(subscription) %></td>
        <td><%= link_to 'Destroy', subscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subscription', new_subscription_path %>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form' %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subscriptionid:</strong>
  <%= @subscription.subscriptionID %>
</p>

<p>
  <strong>Gamesubsr1:</strong>
  <%= @subscription.gameSubsr1 %>
</p>

<p>
  <strong>Subsctype:</strong>
  <%= @subscription.subscType %>
</p>

<p>
  <strong>Gamesubsr1:</strong>
  <%= @subscription.gameSubsr1 %>
</p>

<p>
  <strong>Subsctype:</strong>
  <%= @subscription.subscType %>
</p>

<p>
  <strong>Gamesubsr1:</strong>
  <%= @subscription.gameSubsr1 %>
</p>

<p>
  <strong>Subsctype:</strong>
  <%= @subscription.subscType %>
</p>

<p>
  <strong>Gamesubsr1:</strong>
  <%= @subscription.gameSubsr1 %>
</p>

<p>
  <strong>Subsctype:</strong>
  <%= @subscription.subscType %>
</p>

<p>
  <strong>Gamesubsr1:</strong>
  <%= @subscription.gameSubsr1 %>
</p>

<p>
  <strong>Subsctype:</strong>
  <%= @subscription.subscType %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>